# Generated by Django 5.2.13 on 2026-04-10 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_contact"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="description",
        ),
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.CharField(
                choices=[
                    ("mobile", "Mobile"),
                    ("laptop", "Laptop"),
                    ("tv", "TV"),
                    ("accessories", "Accessories"),
                ],
                default="mobile",
                max_length=20,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(max_length=100),
        ),
    ]
